# Site settings
title: ES6 and ES5 difference in using props
header-img: img/home-bg.png
email: ff18qd@gmail.com
copyright_name: ff18qd
description: > # this means to ignore newlines until "baseurl:"
  when to use this.props when to use props
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ff18qd
learn_profile: ff18qd
email_username: ff18qd@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
